# Generated by Django 2.0.5 on 2018-06-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0003_auto_20180606_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AlterField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(default=None, upload_to='img/portrait', verbose_name='头像'),
        ),
    ]
