# Generated by Django 2.0.5 on 2018-06-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0006_remove_user_head_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('ISBN', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='书籍名称')),
                ('price', models.PositiveIntegerField(default='0', verbose_name='价格')),
                ('book_image', models.ImageField(upload_to='book_image/', verbose_name='书籍图片')),
                ('category', models.CharField(choices=[('Math', '数学'), ('Computer', '计算机'), ('English', '英语'), ('Art', '艺术'), ('Literature', '文学'), ('Project', '工程'), ('Other', '其他')], max_length=10, verbose_name='类别')),
                ('description', models.TextField(verbose_name='描述')),
                ('version', models.CharField(max_length=10, verbose_name='版本')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-add_time'],
            },
        ),
    ]
