# Generated by Django 2.0.5 on 2018-06-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0007_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(default='0', verbose_name='价格'),
        ),
    ]
