# Generated by Django 2.0.5 on 2018-06-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0008_auto_20180607_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=50, verbose_name='书籍名称'),
        ),
    ]
