# Generated by Django 2.0.5 on 2018-06-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0009_auto_20180607_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='版本'),
        ),
    ]
