# Generated by Django 2.0.5 on 2018-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0010_auto_20180607_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='old_price',
            field=models.FloatField(default=0, verbose_name='以前价格'),
        ),
        migrations.AddField(
            model_name='books',
            name='sale_volume',
            field=models.PositiveIntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='books',
            name='storage',
            field=models.PositiveIntegerField(default=1, verbose_name='库存'),
        ),
    ]
