# Generated by Django 2.0.5 on 2018-06-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0012_auto_20180608_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='数量')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.Books', verbose_name='书籍')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('trade_time', models.DateTimeField(auto_now_add=True, verbose_name='交易日期')),
                ('books', models.ManyToManyField(through='shopstore.BooksOrder', to='shopstore.Books', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-trade_time'],
            },
        ),
        migrations.AddField(
            model_name='booksorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.Order', verbose_name='订单'),
        ),
    ]
