# Generated by Django 2.0.5 on 2018-06-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0013_auto_20180608_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='数量')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.Books', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '书籍--购物车',
                'verbose_name_plural': '书籍-购物车',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ManyToManyField(through='shopstore.BookCart', to='shopstore.Books', verbose_name='书籍')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopstore.User', verbose_name='所有者')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.AlterModelOptions(
            name='booksorder',
            options={'verbose_name': '订单_书籍关系表', 'verbose_name_plural': '订单--书籍'},
        ),
        migrations.AddField(
            model_name='bookcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.Cart', verbose_name='购物车'),
        ),
    ]
