# Generated by Django 2.0.5 on 2018-06-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0014_auto_20180608_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='数量')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.Books', verbose_name='加入购物车的书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopstore.User', verbose_name='用户')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookcart',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BookCart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ManyToManyField(through='shopstore.BooksUser', to='shopstore.User', verbose_name='用户'),
        ),
    ]
