# Generated by Django 2.0.5 on 2018-06-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0015_auto_20180608_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksuser',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Finance', '金融'), ('Management', '管理'), ('Math', '数学'), ('Computer', '计算机'), ('English', '英语'), ('Art', '艺术'), ('Literature', '文学'), ('Project', '工程'), ('Other', '其他')], max_length=10, verbose_name='类别'),
        ),
    ]
