# Generated by Django 2.0.5 on 2018-06-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0016_auto_20180611_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booksuser',
            unique_together={('book', 'user')},
        ),
    ]
