# Generated by Django 2.0.5 on 2018-06-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0017_auto_20180619_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=50, verbose_name='余额'),
        ),
    ]
