# Generated by Django 2.0.5 on 2018-06-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopstore', '0018_auto_20180619_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=50, verbose_name='余额'),
        ),
    ]
